---

- name: Install node_exporter package
  community.general.pkgng:
    name: node_exporter
    state: present

- name: Enable node_exporter service
  community.general.sysrc:
    name: node_exporter_enable
    value: "YES"

- name: enable node_exporter at startup
  service:
    name: node_exporter
    state: started
    enabled: yes
