---

- name: Unarchive Node exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy Node exporter to /usr/local/bin
  copy:
    remote_src: yes
    src: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: 0755
  notify: restart node_exporter

- name: Copy the node_exporter systemd service file
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter
