---

- name: Install on Debian or RedHat OS families
  include_tasks: Debian-RedHat.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: Install on FreeBSD
  include_tasks: FreeBSD.yml
  when: ansible_os_family == "FreeBSD"
